
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.64
distribution_type: module
version: 1.00
name: Parse-CSV
author: Adam Kennedy <adamk@cpan.org>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  perl: 5.005
  Params::Util: 0.17
  IO::File: 0
  Text::CSV_XS: 0.23
  Carp: 0
abstract: Highly flexible CVS parser for large files
