---
abstract: 'Highly flexible CSV parser for large files'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  File::Spec: 0.80
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Parse::CSV
name: Parse-CSV
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  IO::File: 1.14
  Params::Util: 0.22
  Text::CSV_XS: 0.42
  perl: 5.005
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Parse-CSV
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Parse-CSV
version: 1.99
