abstract: Highly flexible CVS parser for large files
author: Adam Kennedy <adamk@cpan.org<
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: Parse-CSV
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  IO::File: 0
  Params::Util: 0.17
  Text::CSV_XS: 0.23
  perl: 5.005
version: 0.01
